"""Turn a plot request into a standalone matplotlib script.

xplot always draws by running the script made here. An exported script (``--script``)
therefore reproduces the on-screen figure exactly, and needs only numpy and
matplotlib.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from . import __version__
from .datfile import DatError, DatFile

MODES = ("timeseries", "phase", "phase3d", "bifurcation")


@dataclass
class PlotSpec:
    """What to draw. Column names must already be resolved (see ``DatFile.resolve``)."""

    mode: str = "timeseries"
    x: str | None = None
    y: list[str] = field(default_factory=list)
    z: str | None = None
    subplots: bool = False
    points: bool = False
    par: int = 1                      # allinfo: plot against par1 or par2
    title: str | None = None
    xlabel: str | None = None
    ylabel: str | None = None
    xlim: tuple[float, float] | None = None
    ylim: tuple[float, float] | None = None
    logx: bool = False
    logy: bool = False
    save: list[str] = field(default_factory=list)
    dpi: int = 150


def _rel(target: str | Path, script_dir: Path) -> str:
    """Path of ``target`` relative to the script folder if inside it, else absolute."""
    target = Path(target).resolve()
    try:
        return target.relative_to(script_dir).as_posix()
    except ValueError:
        return target.as_posix()  # HERE / absolute path -> absolute path


def _check(spec: PlotSpec, dats: list[DatFile]) -> None:
    if spec.mode not in MODES:
        raise DatError(f"unknown plot mode '{spec.mode}'")
    kinds = {d.kind for d in dats}
    if len(kinds) > 1:
        raise DatError("all files in one plot must be the same kind (simulation or diagram)")
    if spec.mode == "bifurcation":
        if len(dats) != 1:
            raise DatError("bifurcation diagrams take exactly one file")
        if dats[0].kind == "sim":
            raise DatError(f"{dats[0].path.name} is simulation output, not an AUTO diagram")
        return
    if dats[0].kind != "sim":
        raise DatError(f"{dats[0].path.name} is an AUTO diagram; use the bifurcation plot")
    if len({tuple(d.columns) for d in dats}) > 1:
        raise DatError("files overlaid in one plot must have the same columns")
    needed = {"timeseries": 1, "phase": 2, "phase3d": 3}[spec.mode]
    if spec.mode == "timeseries" and not spec.y:
        raise DatError("choose at least one y column")
    if spec.mode != "timeseries" and len([c for c in (spec.x, *spec.y[:1], spec.z) if c]) < needed:
        raise DatError(f"{spec.mode} needs {needed} columns")


def _header(dats: list[DatFile], spec: PlotSpec, script_dir: Path) -> list[str]:
    d0 = dats[0]
    files = [_rel(d.path, script_dir) for d in dats]
    out = [
        "#!/usr/bin/env python3",
        f'"""{spec.mode} plot of {", ".join(Path(f).name for f in files)}',
        "",
        f"Generated by xplot {__version__}. Edit freely: needs only numpy + matplotlib.",
        '"""',
        "from pathlib import Path",
        "",
        "import matplotlib.pyplot as plt",
        "import numpy as np",
        "",
        "HERE = Path(__file__).resolve().parent",
        f"FILES = {files!r}",
        f"COLUMNS = {d0.columns!r}",
        f"LOAD_OPTIONS = {d0.load_kwargs!r}",
        "",
        "",
        "def load(name):",
        '    """Read one XPPAUT .dat file into a {column name: values} dict."""',
        "    data = np.loadtxt(HERE / name, ndmin=2, **LOAD_OPTIONS)",
        "    return dict(zip(COLUMNS, data.T))",
        "",
        "",
        "runs = {Path(name).stem: load(name) for name in FILES}",
        "",
    ]
    return out


def _sim_body(spec: PlotSpec) -> list[str]:
    fmt = "'.'" if spec.points else "'-'"
    style = "markersize=2" if spec.points else "linewidth=1.2"
    if spec.mode == "timeseries":
        out = [f"X = {spec.x!r}", f"Y = {spec.y!r}", ""]
        if spec.subplots:
            out += [
                "fig, axes = plt.subplots(len(Y), 1, sharex=True, squeeze=False,",
                "                         figsize=(8, 1.2 + 2.2 * len(Y)))",
                "for ax, y in zip(axes[:, 0], Y):",
                "    for run, col in runs.items():",
                f"        ax.plot(col[X], col[y], {fmt}, {style}, label=run)",
                "    ax.set_ylabel(y)",
                "    ax.grid(alpha=0.3)",
                "    if len(runs) > 1:",
                "        ax.legend(fontsize='small')",
                "ax = axes[-1, 0]",
                "ax.set_xlabel(X)",
            ]
        else:
            out += [
                "fig, ax = plt.subplots(figsize=(8, 5))",
                "for run, col in runs.items():",
                "    for y in Y:",
                "        label = y if len(runs) == 1 else f'{y} ({run})'",
                f"        ax.plot(col[X], col[y], {fmt}, {style}, label=label)",
                "ax.set_xlabel(X)",
                "if len(Y) == 1:",
                "    ax.set_ylabel(Y[0])",
                "if len(Y) > 1 or len(runs) > 1:",
                "    ax.legend()",
                "ax.grid(alpha=0.3)",
            ]
        return out

    if spec.mode == "phase":
        return [
            f"X, Y = {spec.x!r}, {spec.y[0]!r}",
            "",
            "fig, ax = plt.subplots(figsize=(6.5, 6))",
            "for run, col in runs.items():",
            f"    line, = ax.plot(col[X], col[Y], {fmt}, {style}, label=run)",
            "    ax.plot(col[X][0], col[Y][0], 'o', color=line.get_color(), markersize=5)  # start point",
            "ax.set_xlabel(X)",
            "ax.set_ylabel(Y)",
            "if len(runs) > 1:",
            "    ax.legend()",
            "ax.grid(alpha=0.3)",
        ]

    # phase3d
    return [
        f"X, Y, Z = {spec.x!r}, {spec.y[0]!r}, {spec.z!r}",
        "",
        "fig = plt.figure(figsize=(7, 6.5))",
        "ax = fig.add_subplot(projection='3d')",
        "for run, col in runs.items():",
        f"    ax.plot(col[X], col[Y], col[Z], {fmt}, {style}, label=run)",
        "ax.set_xlabel(X)",
        "ax.set_ylabel(Y)",
        "ax.set_zlabel(Z)",
        "if len(runs) > 1:",
        "    ax.legend()",
    ]


_BIF_STYLE = [
    "# XPPAUT colours: red = stable equilibria, black = unstable equilibria,",
    "# green filled = stable periodic orbits, blue open = unstable periodic orbits.",
    "STYLE = {",
    "    1: dict(label='stable equilibrium', color='tab:red', linestyle='-', linewidth=2),",
    "    2: dict(label='unstable equilibrium', color='black', linestyle='--', linewidth=1),",
    "    3: dict(label='stable periodic (max/min)', color='tab:green', linestyle='none',",
    "            marker='o', markersize=3),",
    "    4: dict(label='unstable periodic (max/min)', color='tab:blue', linestyle='none',",
    "            marker='o', markersize=3, markerfacecolor='none'),",
    "}",
    "",
    "",
    "def segments(typ, br):",
    '    """Split row indices into runs that share a stability type and branch."""',
    "    cut = np.flatnonzero((np.diff(typ) != 0) | (np.diff(br) != 0)) + 1",
    "    return np.split(np.arange(len(typ)), cut)",
    "",
    "",
]


def _bif_body(spec: PlotSpec, dat: DatFile) -> list[str]:
    var = spec.y[0] if spec.y else dat.variables[0]
    if dat.kind == "diagram":
        out = [
            "col = next(iter(runs.values()))",
            "par = col['par']",
            f"hi, lo = col[{dat.columns[1]!r}], col[{dat.columns[2]!r}]",
            "typ, br = col['type'].astype(int), col['branch'].astype(int)",
        ]
        xlabel, ylabel = "parameter", var
    else:
        par_name = f"par{spec.par}"
        out = ["col = next(iter(runs.values()))", f"par = col[{par_name!r}]"]
        if var == "period":
            out.append("hi = lo = col['period']")
        else:
            out.append(f"hi, lo = col[{var + '_hi'!r}], col[{var + '_lo'!r}]")
        out.append("typ, br = col['type'].astype(int), col['branch'].astype(int)")
        xlabel, ylabel = par_name, var
    only_periodic = dat.kind == "allinfo" and var == "period"
    out += [
        "",
        *_BIF_STYLE,
        "fig, ax = plt.subplots(figsize=(8, 5.5))",
        "labelled = set()",
        "for seg in segments(typ, br):",
        "    kind = int(typ[seg[0]])",
        f"    if kind not in STYLE{' or kind in (1, 2)' if only_periodic else ''}:",
        "        continue",
        "    style = dict(STYLE[kind])",
        "    if kind in labelled:",
        "        style.pop('label')",
        "    labelled.add(kind)",
        "    if kind in (1, 2):",
        "        # join to the next point so stable/unstable pieces meet without a gap",
        "        nxt = seg[-1] + 1",
        "        if nxt < len(typ) and br[nxt] == br[seg[0]] and typ[nxt] in (1, 2):",
        "            seg = np.append(seg, nxt)",
        "        ax.plot(par[seg], hi[seg], **style)",
        "    else:",
        "        ax.plot(par[seg], hi[seg], **style)",
        "        style.pop('label', None)",
        "        ax.plot(par[seg], lo[seg], **style)",
        f"ax.set_xlabel({xlabel!r})",
        f"ax.set_ylabel({ylabel!r})",
        "ax.legend(fontsize='small')",
        "ax.grid(alpha=0.3)",
    ]
    return out


def _footer(spec: PlotSpec, script_dir: Path, show: bool) -> list[str]:
    out = [""]
    if spec.title:
        out.append(f"ax.set_title({spec.title!r})" if spec.mode != "timeseries" or not spec.subplots
                   else f"fig.suptitle({spec.title!r})")
    if spec.xlabel:
        out.append(f"ax.set_xlabel({spec.xlabel!r})")
    if spec.ylabel:
        out.append(f"ax.set_ylabel({spec.ylabel!r})")
    if spec.xlim:
        out.append(f"ax.set_xlim({spec.xlim[0]!r}, {spec.xlim[1]!r})")
    if spec.ylim:
        out.append(f"ax.set_ylim({spec.ylim[0]!r}, {spec.ylim[1]!r})")
    if spec.logx:
        out.append("ax.set_xscale('log')")
    if spec.logy:
        out.append("ax.set_yscale('log')")
    out.append("fig.tight_layout()")
    for target in spec.save:
        out.append(f"fig.savefig(HERE / {_rel(target, script_dir)!r}, dpi={spec.dpi})")
    if show:
        out.append("plt.show()")
    return out


def build_script(spec: PlotSpec, dats: list[DatFile], script_path: str | Path, show: bool = True) -> str:
    """Return Python source that draws ``spec`` from ``dats``.

    ``script_path`` is where the script will (or would) live. Data and output
    paths are written relative to it.
    """
    _check(spec, dats)
    script_dir = Path(script_path).resolve().parent
    lines = _header(dats, spec, script_dir)
    if spec.mode == "bifurcation":
        lines += _bif_body(spec, dats[0])
    else:
        lines += _sim_body(spec)
    lines += _footer(spec, script_dir, show)
    return "\n".join(lines) + "\n"


def run_script(source: str, script_path: str | Path, headless: bool = False) -> None:
    """Execute generated source as if it were saved at ``script_path``.

    ``headless`` switches matplotlib to the non-GUI Agg backend. Use it for
    one-shot "save only" runs. Interactive sessions leave it off so that later
    plots can still open windows.
    """
    import matplotlib

    if headless:
        matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    path = str(Path(script_path).resolve())
    namespace = {"__name__": "__main__", "__file__": path}
    try:
        exec(compile(source, path, "exec"), namespace)
    finally:
        plt.close("all")
